display_name: Panorama Secure Access
package_name: panorama-secure-access
maintainer:
  name: Panorama Scholarly Group
  email: contact@panorama-sg.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - Panorama Secure Access
  - Clash
  - ClashMeta
  - Proxy

generic_name: Panorama Secure Access

categories:
  - Network

startup_notify: true
